version: '2'
services:
  restyaboard:
    build: .
    ports:
      - 1234:80
    volumes:
       - /var/opt/restya/media:/usr/share/nginx/html/media
       - /var/opt/restya/img/large_thumb:/usr/share/nginx/html/client/img/large_thumb
       - /var/opt/restya/img/micro_thumb:/usr/share/nginx/html/client/img/micro_thumb
       - /var/opt/restya/img/small_thumb:/usr/share/nginx/html/client/img/small_thumb
       - /var/opt/restya/img/normal_thumb:/usr/share/nginx/html/client/img/normal_thumb
       - /var/opt/restya/img/medium_thumb:/usr/share/nginx/html/client/img/medium_thumb
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
      - SMTP_DOMAIN=domain
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=pass
      - SMTP_SERVER=server
      - SMTP_PORT=465
      - TZ=Etc/UTC
    depends_on:
      - postgres
    restart: always
  postgres:
    image: onjin/alpine-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
